export const SOURCE_IMAGE_SIZE_PX = 768;
export const SHELF_IMAGE_ASPECT_RATIO = 0.2;
export const SUBGROUP_IMAGE_ASPECT_RATIO = 0.05;

export const SHELF_RENDER_IMAGE_SIZE_PX = SOURCE_IMAGE_SIZE_PX * SHELF_IMAGE_ASPECT_RATIO;
export const SUBGROUP_RENDER_IMAGE_SIZE_PX = SOURCE_IMAGE_SIZE_PX * SUBGROUP_IMAGE_ASPECT_RATIO;
