# Tokens observed in ``title_cols.csv`` (whole-word animal / mythical-creature vocabulary).
# BROAD_* are generic; LITERAL_SPECIES are concrete names used for matching.

BROAD_ZOOLOGICAL_DESCRIPTORS = [
    "animal",
    "animals",
    "bird",
    "birds",
    "feline",
    "fish",
    "quadruped",
    "serpent",
]

# Species and cataloguing labels for composite/mythical beasts (alphabetical).
LITERAL_SPECIES = [
    "antelope",
    "bat",
    "bear",
    "buffalo",
    "bull",
    "butterfly",
    "camel",
    "carp",
    "cat",
    "chicken",
    "chimera",
    "crab",
    "crane",
    "deer",
    "dog",
    "donkey",
    "dragon",
    "duck",
    "eagle",
    "elephant",
    "falcon",
    "fox",
    "frog",
    "goat",
    "goose",
    "hawk",
    "hare",
    "horse",
    "kirin",
    "lamb",
    "lion",
    "llama",
    "lobster",
    "lizard",
    "monkey",
    "mouse",
    "otter",
    "owl",
    "ox",
    "parrot",
    "peacock",
    "phoenix",
    "pig",
    "rabbit",
    "ram",
    "rooster",
    "salamander",
    "shark",
    "snake",
    "siren",
    "stag",
    "starfish",
    "swan",
    "tiger",
    "turkey",
    "turtle",
    "whale",
]
